title: RZTech
description: A collection of my technical writings.
baseurl: "/tech-articles" # the subpath of your site, e.g. /blog
url: "https://msmriyaz.github.io" # your domain without the baseurl
# theme: minima # We're using our own custom styles instead

# Permalink pattern for posts
permalink: /:year/:month/:day/:title:output_ext

# Plugins
plugins:
  - jekyll-feed

# Feed settings
feed:
  path: feed.xml