title: RZTech
description: A collection of my technical writings.
baseurl: "/tech-articles" # or "" if it is in the root of your username.github.io
url: "https://msmriyaz.github.io" # your domain without the baseurl
# theme: minima # We're using our own custom styles instead

# Permalink pattern for posts (ignores categories)
permalink: /:year/:month/:day/:title:output_ext

# Plugins
plugins:
  - jekyll-feed

# Feed settings
feed:
  path: feed.xml